version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" # Expose the PostgreSQL port on the host
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data between container restarts

volumes:
  pgdata:
